import "./globals.css";
import type { Metadata } from "next";
import { Inter, IBM_Plex_Sans, IBM_Plex_Mono } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });
const plexSans = IBM_Plex_Sans({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-ibm",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <title>Marin is the cutest!</title>
        <link rel="icon" type="image/x-icon" href="/images/favicon.ico" />
      </head>
      <body
        className={`${inter.variable} font-sans  ${plexSans.variable} font-plex`}
      >
        <div className="absolute bottom-0 text-[12px] text-black z-50 right-24">
          Designed and Developed by{" "}
          <Link href="https://github.com/a-me-lia" className="underline">
            Marin Kurokawa
          </Link>{" "}
          ©2023
        </div>
        {children}
      </body>
    </html>
  );
}
